version: '3.8'

services:
  db:
    container_name: stripe-db
    image: supabase/postgres:15.1.0.86
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped
    ports:
      - 55432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../db/migrations:/docker-entrypoint-initdb.d
